### ISSUE TITLE
Device is recognized but inputs are not received. 

### ISSUE THREAD

**Issue by Airister** [microsoft/RdpGamepad#8]
Pretty much what the title says, the device is detected but the inputs of the device are not received by the rdp.

**Comment by jpflouret** [comment]
Do you have an "Xbox 360 Controller for Windows" show up in device manager on your remote computer? Should look something like this:
![image](https://user-images.githubusercontent.com/9397098/78595749-68fd0680-77ff-11ea-9793-75151be24e94.png)

**Comment by Airister** [comment]
Yes I do.
![image](https://user-images.githubusercontent.com/25807890/87449714-86dec200-c5cb-11ea-9e7f-cf44c625a9a2.png)

**Comment by jpflouret** [comment]
That is the virtual controller that is being fed by the remote desktop receiver so it looks to be working. If your tool or game is able to read from an Xbox 360 controller then this should just work. What tool or engine do you use? Is this tool/engine/game using Xinput for controller input? Does it detect the device as device 0? When you read the input state from the controller, is the data updating?

**Comment by Airister** [comment]
I’m using X-Plane and I have no idea. It was working the first time and then just stopped. What is device0? And wdym by the last sentence

**Comment by Airister** [comment]
It works fine on my host pc

**Comment by jpflouret** [comment]
I meant if you are programming and using XInput and if you are getting a value out of that API. I don't know what X-Plane uses for input. I would suggest trying something else, perhaps something like [this Xbox 360 Controller Tester](https://github.com/nenslen/xbox-360-controller-tester). That way you can test whethere the controller data is being received or not. I may extend the receiver applet to show you the received controller data.

**Comment by Airister** [comment]
I used an HTML one online, data is not being received.

**Comment by jpflouret** [comment]
I am sorry I cannot reproduce this. Could you point me to the tool you used to test this?

**Comment by mechachiken** [comment]
I have something like this issue and I'm pretty sure it's because there's a physical controller connected to the remote pc. I am unable to control the remote game with my local controller but I can see in the direct x control panel settings on the remote machine that the local controller input is being received. However if I play a two player split screen session on my remote machine then my local pad controls player 2.

Perhaps that's your issue as well Airister?

**Comment by jpflouret** [comment]
That is correct. The Remote Desktop Gamepad receiver adds a new controller and does not replace any existing controllers that you have physically plugged in to the remote computer. If your game always uses “the first controller” then it is possible that you’ll run I to this issue. I think that would be an issue with your game rather than an issue with RdpGamepad.

Many games have a “Press Start” or “Press A” screen from where they listen to all controllers and then just bind your user with the controller you pressed the button on.

Could you try unplugging all controllers from the remote computer?

**Comment by mechachiken** [comment]
Yep, disconnecting the controller on the remote pc and rebooting fixed the issue for me. I can now use a local controller to control gameplay on a remote machine.

**Comment by BaeMinCheon** [comment]
thanks guys, i have been suffered with this issue and thought as only my own issue. but now cleared there was the caution.

anyway, i also found that unplugging real controller connected with remote pc is exactly the solution, and you can unplug the real controller by disabling device in control panel unless commute to office.

**Comment by jpflouret** [comment]
I’ll add some documentation to the fact that this plugin _adds_ a new controller rather than replace your existing plugged in controller.
